version: '3.8'

services:
  # PostgreSQL Master - Centro Quito
  postgres-master:
    image: postgres:13
    container_name: centro-quito-master
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: adminhospital
      POSTGRES_PASSWORD: 12345Aa!
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - ./database/scripts/init-master.sql:/docker-entrypoint-initdb.d/init-master.sql
      #- ./database/replication/master-config:/etc/postgresql/
      - postgres_master_data:/var/lib/postgresql/data
    networks:
      - hospital-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminhospital -d hospital_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: |
      postgres
      -c wal_level=replica
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby=on

  # PostgreSQL Slave 1 - Centro Guayaquil
  postgres-slave1:
    image: postgres:13
    container_name: centro-guayaquil-slave
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: adminhospital
      POSTGRES_PASSWORD: 12345Aa!
    ports:
      - "5433:5432"
    volumes:
      - ./database/scripts/init-slave.sql:/docker-entrypoint-initdb.d/init-slave.sql
      #- ./database/replication/slave1-config:/etc/postgresql/
      - postgres_slave1_data:/var/lib/postgresql/data
    networks:
      - hospital-network
    depends_on:
      - postgres-master
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminhospital -d hospital_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: |
      bash -c "
        until pg_isready -h postgres-master -p 5432 -U adminhospital; do
          echo 'Esperando al servidor master...'
          sleep 5
        done
        exec docker-entrypoint.sh postgres
      "

  # PostgreSQL Slave 2 - Centro Cuenca
  postgres-slave2:
    image: postgres:13
    container_name: centro-cuenca-slave
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: adminhospital
      POSTGRES_PASSWORD: 12345Aa!
    ports:
      - "5434:5432"
    volumes:
      - ./database/scripts/init-slave.sql:/docker-entrypoint-initdb.d/init-slave.sql
      #- ./database/replication/slave2-config:/etc/postgresql/
      - postgres_slave2_data:/var/lib/postgresql/data
    networks:
      - hospital-network
    depends_on:
      - postgres-master
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminhospital -d hospital_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: |
      bash -c "
        until pg_isready -h postgres-master -p 5432 -U adminhospital; do
          echo 'Esperando al servidor master...'
          sleep 5
        done
        exec docker-entrypoint.sh postgres
      "

volumes:
  postgres_master_data:
  postgres_slave1_data:
  postgres_slave2_data:

networks:
  hospital-network:
    driver: bridge